# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # AdditionalModelParameters Model.
  class AdditionalModelParameters < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :field

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address

    # TODO: Write general description for this method
    # @return [Job]
    attr_accessor :job

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['field'] = 'field'
      @_hash['address'] = 'address'
      @_hash['job'] = 'Job'
      @_hash
    end

    def initialize(job = nil,
                   address = nil,
                   field = nil,
                   name = nil,
                   additional_properties = {})
      @name = name
      @field = field
      @address = address
      @job = job

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      job = Job.from_hash(hash['Job']) if hash['Job']
      address = hash['address']
      field = hash['field']
      name = hash['name']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      AdditionalModelParameters.new(job,
                                    address,
                                    field,
                                    name,
                                    hash)
    end
  end
end
