# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'company'

module Tester
  # BossCompany Model.
  class BossCompany < Company
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :first_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_boss

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_name'] = 'first name'
      @_hash['last_name'] = 'last name'
      @_hash['address_boss'] = 'address_boss'
      @_hash = super().merge(@_hash)
      @_hash
    end

    def initialize(address = nil,
                   address_boss = nil,
                   cell_number = nil,
                   company_name = nil,
                   first_name = nil,
                   last_name = nil,
                   company = nil,
                   additional_properties = {})
      @first_name = first_name
      @last_name = last_name
      @address_boss = address_boss

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      # Call the constructor of the base class
      super(address,
            cell_number,
            company_name,
            company)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address = hash['address']
      address_boss = hash['address_boss']
      cell_number = hash['cell number']
      company_name = hash['company name']
      first_name = hash['first name']
      last_name = hash['last name']
      company = hash['company']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      BossCompany.new(address,
                      address_boss,
                      cell_number,
                      company_name,
                      first_name,
                      last_name,
                      company,
                      hash)
    end
  end
end
