# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # GlossDiv Model.
  class GlossDiv < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [GlossList]
    attr_accessor :gloss_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['title'] = 'title'
      @_hash['gloss_list'] = 'GlossList'
      @_hash
    end

    def initialize(gloss_list = nil,
                   title = nil,
                   additional_properties = {})
      @title = title
      @gloss_list = gloss_list

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      gloss_list = GlossList.from_hash(hash['GlossList']) if hash['GlossList']
      title = hash['title']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      GlossDiv.new(gloss_list,
                   title,
                   hash)
    end
  end
end
