# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # GlossList Model.
  class GlossList < BaseModel
    # TODO: Write general description for this method
    # @return [GlossEntry]
    attr_accessor :gloss_entry

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['gloss_entry'] = 'GlossEntry'
      @_hash
    end

    def initialize(gloss_entry = nil,
                   additional_properties = {})
      @gloss_entry = gloss_entry

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      gloss_entry = GlossEntry.from_hash(hash['GlossEntry']) if
        hash['GlossEntry']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      GlossList.new(gloss_entry,
                    hash)
    end
  end
end
