# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # language_enum.
  class LanguageEnum
    LANGUAGE_ENUM = [
      # TODO: Write general description for EN
      EN = 'EN'.freeze,

      # TODO: Write general description for DZ
      DZ = 'DZ'.freeze,

      # TODO: Write general description for NL
      NL = 'NL'.freeze
    ].freeze
  end
end
