# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # ParamFormat.
  class ParamFormat
    PARAM_FORMAT = [
      # TODO: Write general description for TEMPLATE
      TEMPLATE = 'Template'.freeze,

      # TODO: Write general description for FORM
      FORM = 'Form'.freeze,

      # TODO: Write general description for BODY
      BODY = 'Body'.freeze,

      # TODO: Write general description for HEADER
      HEADER = 'Header'.freeze,

      # TODO: Write general description for QUERY
      QUERY = 'Query'.freeze
    ].freeze
  end
end
