# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # PrecisionAsOptional Model.
  class PrecisionAsOptional < BaseModel
    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :precision

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['precision'] = 'precision'
      @_hash
    end

    def initialize(precision = nil,
                   additional_properties = {})
      @precision = precision

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      precision = hash['precision']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PrecisionAsOptional.new(precision,
                              hash)
    end
  end
end
