# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # RedirectSettings Model.
  class RedirectSettings < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :redirect_mode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['redirect_mode'] = 'redirectMode'
      @_hash
    end

    def initialize(redirect_mode = nil,
                   additional_properties = {})
      @redirect_mode = redirect_mode

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      redirect_mode = hash['redirectMode']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      RedirectSettings.new(redirect_mode,
                           hash)
    end
  end
end
