# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # ResponseWithEnum Model.
  class ResponseWithEnum < BaseModel
    # TODO: Write general description for this method
    # @return [ParamFormat]
    attr_accessor :param_format

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :optional

    # TODO: Write general description for this method
    # @return [Type]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :constant

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_array

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_stream

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_attribute

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_map

    # TODO: Write general description for this method
    # @return [Attributes]
    attr_accessor :attributes

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :nullable

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['param_format'] = 'paramFormat'
      @_hash['optional'] = 'optional'
      @_hash['type'] = 'type'
      @_hash['constant'] = 'constant'
      @_hash['is_array'] = 'isArray'
      @_hash['is_stream'] = 'isStream'
      @_hash['is_attribute'] = 'isAttribute'
      @_hash['is_map'] = 'isMap'
      @_hash['attributes'] = 'attributes'
      @_hash['nullable'] = 'nullable'
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['description'] = 'description'
      @_hash
    end

    def initialize(attributes = nil,
                   constant = nil,
                   description = nil,
                   id = nil,
                   is_array = nil,
                   is_attribute = nil,
                   is_map = nil,
                   is_stream = nil,
                   name = nil,
                   nullable = nil,
                   optional = nil,
                   param_format = nil,
                   type = nil,
                   additional_properties = {})
      @param_format = param_format
      @optional = optional
      @type = type
      @constant = constant
      @is_array = is_array
      @is_stream = is_stream
      @is_attribute = is_attribute
      @is_map = is_map
      @attributes = attributes
      @nullable = nullable
      @id = id
      @name = name
      @description = description

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      attributes = Attributes.from_hash(hash['attributes']) if
        hash['attributes']
      constant = hash['constant']
      description = hash['description']
      id = hash['id']
      is_array = hash['isArray']
      is_attribute = hash['isAttribute']
      is_map = hash['isMap']
      is_stream = hash['isStream']
      name = hash['name']
      nullable = hash['nullable']
      optional = hash['optional']
      param_format = hash['paramFormat']
      type = hash['type']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      ResponseWithEnum.new(attributes,
                           constant,
                           description,
                           id,
                           is_array,
                           is_attribute,
                           is_map,
                           is_stream,
                           name,
                           nullable,
                           optional,
                           param_format,
                           type,
                           hash)
    end
  end
end
