# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # ResponseData Model.
  class ResponseData < BaseModel
    # TODO: Write general description for this method
    # @return [Feed]
    attr_accessor :feed

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['feed'] = 'feed'
      @_hash
    end

    def initialize(feed = nil,
                   additional_properties = {})
      @feed = feed

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      feed = Feed.from_hash(hash['feed']) if hash['feed']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      ResponseData.new(feed,
                       hash)
    end
  end
end
