# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # team_integer.
  class TeamInteger
    TEAM_INTEGER = [
      # TODO: Write general description for CODEGEN
      CODEGEN = 1,

      # TODO: Write general description for CGAAS
      CGAAS = 2,

      # TODO: Write general description for UX
      UX = 3,

      # TODO: Write general description for QA
      QA = 4
    ].freeze
  end
end
