# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # team.
  class Team
    TEAM = [
      # TODO: Write general description for CODEGEN
      CODEGEN = 'codegen'.freeze,

      # TODO: Write general description for CGAAS
      CGAAS = 'cgaas'.freeze,

      # TODO: Write general description for UX
      UX = 'ux'.freeze,

      # TODO: Write general description for QA
      QA = 'qa'.freeze
    ].freeze
  end
end
