# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  #  tester client class.
  class Client
    attr_reader :config

    # Access to response_types controller.
    # @return [ResponseTypesController] Returns the controller instance.
    def response_types
      @response_types ||= ResponseTypesController.new config
    end

    # Access to form_params controller.
    # @return [FormParamsController] Returns the controller instance.
    def form_params
      @form_params ||= FormParamsController.new config
    end

    # Access to body_params controller.
    # @return [BodyParamsController] Returns the controller instance.
    def body_params
      @body_params ||= BodyParamsController.new config
    end

    # Access to error_codes controller.
    # @return [ErrorCodesController] Returns the controller instance.
    def error_codes
      @error_codes ||= ErrorCodesController.new config
    end

    # Access to query_param controller.
    # @return [QueryParamController] Returns the controller instance.
    def query_param
      @query_param ||= QueryParamController.new config
    end

    # Access to echo controller.
    # @return [EchoController] Returns the controller instance.
    def echo
      @echo ||= EchoController.new config
    end

    # Access to header controller.
    # @return [HeaderController] Returns the controller instance.
    def header
      @header ||= HeaderController.new config
    end

    # Access to template_params controller.
    # @return [TemplateParamsController] Returns the controller instance.
    def template_params
      @template_params ||= TemplateParamsController.new config
    end

    # Access to query_params controller.
    # @return [QueryParamsController] Returns the controller instance.
    def query_params
      @query_params ||= QueryParamsController.new config
    end

    def initialize(timeout: 60, max_retries: 3, retry_interval: 1,
                   backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put],
                   environment: Environment::TESTING, port: '80',
                   suites: SuiteCode::HEARTS, config: nil)
      @config = if config.nil?
                  Configuration.new(timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    retry_statuses: retry_statuses,
                                    retry_methods: retry_methods,
                                    environment: environment, port: port,
                                    suites: suites)
                else
                  config
                end
    end
  end
end
