# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # custom error response class.
  class CustomErrorResponseException < APIException
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :error_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :caught

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :exception

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :inner_exception

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @error_description = hash['error description']
      @caught = hash['caught']
      @exception = hash['Exception']
      @inner_exception = hash['Inner Exception']
    end
  end
end
