# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # enum in exception class.
  class EnumInException < APIException
    # TODO: Write general description for this method
    # @return [ParamFormat]
    attr_accessor :param

    # TODO: Write general description for this method
    # @return [Type]
    attr_accessor :type

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @param = hash['param']
      @type = hash['type']
    end
  end
end
