# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Tester
  # Exception with boolean class.
  class ExceptionWithBooleanException < APIException
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :value

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :value1

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @value = hash['value']
      @value1 = hash['value1']
    end
  end
end
