# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Tester
  # rfc 1123 exception class.
  class Rfc1123Exception < APIException
    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :date_time

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :date_time1

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpResponse] The HttpReponse of the API call.
    def initialize(reason, response)
      super(reason, response)
      hash = APIHelper.json_deserialize(@response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @date_time = DateTime.httpdate(hash['dateTime']) if hash['dateTime']
      @date_time1 = DateTime.httpdate(hash['dateTime1']) if hash['dateTime1']
    end
  end
end
