# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'tester'
require_relative '../test_helper'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include Tester

  # Create configuration and set any test parameters
  CONFIG = Configuration.new(port: '3000', suites: SuiteCode::DIAMONDS,
                             environment: Environment::TESTING)
end
