# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class EchoControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    @response_catcher = HttpResponseCatcher.new
    @controller = EchoController.new CONFIG, http_call_back: @response_catcher
  end

  # Todo: Add description for test test_json_echo
  def test_json_echo()
    # Parameters for the API call
    input = JSON.parse(
      '{"uid":"1123213","name":"Shahid"}'
    )

    # Perform the API call through the SDK function
    result = @controller.json_echo(input)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"body":{"uid":"1123213","name":"Shahid"}}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

end
