# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class HeaderControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    @response_catcher = HttpResponseCatcher.new
    @controller = HeaderController.new CONFIG, http_call_back: @response_catcher
  end

  # Todo: Add description for test test_send_headers
  def test_send_headers()
    # Parameters for the API call
    custom_header = 'TestString'
    value = 'TestString'

    # Perform the API call through the SDK function
    result = @controller.send_headers(custom_header, value)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"passed":true}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(TestHelper.match_body(expected_body, received_body, check_values: true))
  end

end
