# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class TemplateParamsControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    @response_catcher = HttpResponseCatcher.new
    @controller = TemplateParamsController.new CONFIG, http_call_back: @response_catcher
  end

  # Todo: Add description for test test_send_string_array
  def test_send_string_array()
    # Parameters for the API call
    strings = APIHelper.json_deserialize(
      '["abc","def"]'
    )

    # Perform the API call through the SDK function
    result = @controller.send_string_array(strings)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

  # Todo: Add description for test test_send_integer_array
  def test_send_integer_array()
    # Parameters for the API call
    integers = APIHelper.json_deserialize(
      '[1,2,3,4,5]'
    )

    # Perform the API call through the SDK function
    result = @controller.send_integer_array(integers)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

end
